### ISSUE TITLE
Action ergaenzen

### ISSUE THREAD

**Issue by JayTee42** [ComputerScienceLecturesTUBAF/SoftwareentwicklungSoSe2020_Aufgabe_01#3]

**Comment by SebastianZug** [comment]
Ich würde aber noch keine spezifischen Tests durchführen, sondern nur evaluieren, ob das Bauen funktioniert. Ich würde die Action auch nur für die Debugging Aufgabe einführen oder?

**Comment by JayTee42** [comment]
Hey :) ja, definitiv. Sorry, ich teste auch gerade nur und war im falschen Repo.
